### ISSUE TITLE
Replace self-hosted Tesseract with https://ocr.space API

### ISSUE THREAD

**Issue by TheLonelyGhost** [GrafeasGroup/tor_ocr#3]
Tesseract transcriptions are taking WAAAAY too long (e.g., 17 minutes) and aren't exactly accurate. A single bot for this absolutely tanks the CPU it's running on as well.

Per discussion with the other maintainers, we believe we should offload this to a service, even if it is a paid one as long as the rates are low. In this case, we've found https://ocr.space to be a sweet spot of quality and price.

Tasks:

- [ ] Replace Tesseract references with HTTP call to [ocr.space API](https://ocr.space/ocrapi)
- [ ] Rate limit to 500 API calls per day, stored in Redis
- [ ] If rate limit reached, do not do anything (e.g., no replies like "rate limit reached")
- [ ] Load API keys (if any) via one or more environment variables

**Comment by perryprog** [comment]
I think this would be a fun weekend project for me, I need something to do. I'm still a pretty big beginner to Python, but I think I can handle it. I've also been talking to @itsthejoker about this.

**Comment by TheLonelyGhost** [comment]
By all means, have at it! I’m neck deep in infrastructure stuff at the moment. Feel free to open a PR with “[WIP]” in the title if you’d like some asynchronous pair programming. Happy to help! 👏
