### ISSUE TITLE
Persist completed attempts to OCR content in a post to Blossom's API.

### ISSUE THREAD

**Issue by TheLonelyGhost** [GrafeasGroup/tor_ocr#30]
Acceptance Criteria:

- Blossom's record of a post is marked as OCR attempted if call to OCR service succeeds (regardless of if it found content)
- Blossom's record of a post is not marked as OCR attempted if a call to OCR service fails

**Comment by itsthejoker** [comment]
Updated flow:

- take the ID that we get from Redis when u/ToR puts in a new post to create an OCR attempt from
- ask Blossom for data at the submission endpoint for this ID
- verify that `has_ocr_transcription` is False
- create and post Transcription object to Blossom for the above submission ID

**Comment by itsthejoker** [comment]
Reworked flow so that this issue is no longer necessary. See https://github.com/GrafeasGroup/tor_ocr/pull/32
