### ISSUE TITLE
RFC: Adding spellcheck to try and filter out obvious junk from automated transcriptions

### ISSUE THREAD

**Issue by itsthejoker** [GrafeasGroup/tor_ocr#38]
It's well-known that u/transcribot tries its best, but sometimes we just end up with pure shit because the technology isn't perfect. I received a suggestion to see about implementing something like https://pypi.org/project/hunspell/ to see if there was a way to reject obvious outliers. The primary issue that I see is that there doesn't seem to be a way to differentiate between "this is almost spelled right" and "this is junk", but that's why this is a RFC.

**Comment by TheLonelyGhost** [comment]
I'm not sure how you're suggesting this be used. `hunspell` to correct the spelling and post it? Using it purely as a litmus test to determine if it's garbage?

If it's the former, I'm not sure that would be wise. All kinds of primary data sources have grammatical and spelling mistakes, hence the whole idea of `[sic]` in quotations.

If a litmus test, determining "junk" status based on spelling, or any other metric, seems pretty tied to underlying meaning of what is in the picture. I'm not sure how effective it would be at rooting out junk OCR attempts, but I'm interested to find out. Show me the data!

**Comment by itsthejoker** [comment]
No data to be shown. The context of the suggestion I received was to automatically fix spelling issues, but as you've already pointed out, that doesn't work well for what we need. If there's no real usage for any other reason for it, then at least we discussed it.

**Comment by TheLonelyGhost** [comment]
The more I consider it, the less of a valid measure of quality it seemed to be. I'm sure we could find better measures if we cared to.

If it was to fix spelling issues, this definitely wouldn't make sense for reasons stated earlier.

Sounds like there isn't much benefit beyond, and even among these two. Consider it discussed. 😅
