### ISSUE TITLE
Respond to users replying to the bot

### ISSUE THREAD

**Issue by TimJentzsch** [GrafeasGroup/tor_ocr#42]
Sometimes users will reply to u/transcribot instead of u/transcribersofreddit, wondering why the bot doesn't reply.

u/transcribot should regularly check its inbox to respond to these people, reminding them that they should use the commands on u/transcribersofreddit instead.

**Comment by crhopkins** [comment]
Should the response be for people who replied to a comment, PM'd the bot, or both?

**Comment by TimJentzsch** [comment]
Responding to comment replies should be enough, as people usually only do it by accident, thinking that they are replying to u/transcribersofreddit instead.

**Comment by crhopkins** [comment]
This can be closed, PR #43 solves it
